cpv: version 0.2

diff --git a/cpv b/cpv
--- a/cpv
+++ b/cpv
@@ -15,7 +15,7 @@ done
 
 if [ $# -lt 2 ]; then
 	APP=${0##*/}
-	VER=0.1
+	VER=0.2
 	echo "$APP $VER">&2
 	echo >&2
 	echo "Syntax: $APP <source file/directory> <destination file/directory>" >&2
@@ -58,6 +58,8 @@ checkBinarys "pv" "chown" "chmod" "find" "mkdir" "du" "tar" "bc"
 PV=tbper
 
 syncPermissions() {
+	# sync only if root
+	[ "$(id -u)" != "0" ] && return
 	chmod --reference="$1" "$2" &&
 	chown --reference="$1" "$2" || {
 		echoError "Error: chmod/chown failed."
@@ -94,11 +96,29 @@ humanReadable() {
 	fi
 }
 
+isFile() {
+	# existing and readable?
+	[ -r "$1" ] &&
+	# not directory
+	[ ! -d "$1" ] &&
+	# not socket
+	[ ! -S "$1" ] &&
+	# not a special file --> /dev/random
+	#i [ ! -c "$1" ] &&
+	# not FIFO
+	[ ! -p "$1" ] &&
+	return 0
+	
+	return 1
+}
+
 if [ $# -eq 2 ]; then
 	[ ! -e "$1" ] && echoError "Error: '$1' does not exist."
+	[ -e "$2" ] && [ ! -w "$2" ] && echoError "Error: '$2' already exist but is not writeable."
 	
 	# file to dir
-	if [ ! -d "$1" ] && [ -r "$1" ] && [ -d "$2" ]; then
+	# if [ ! -d "$1" ] && [ -r "$1" ] && [ -d "$2" ]; then
+	if isFile "$1" && [ -d "$2" ]; then
 		BASE=$(basename "$1")
 		if [ "$(readlink -f "$1")" == "$(readlink -f "$2"/"$BASE")" ]; then
 			echoError "Error: Source and destination file is the same."
@@ -109,13 +129,14 @@ if [ $# -eq 2 ]; then
 		fi
 		SIZEH=$(humanReadable $(stat -c%s "$1") 0)
 		[ -z "$SIZEH" ] && SIZEH=$(stat -c%F "$1")
-		echo -e "${YELLOW}File: $RESET$1 [$SIZEH] $YELLOW-->$RESET $(readlink -f "$2"/"$BASE")" # readlink removes double slash
+		echo "${YELLOW}File: $RESET$1 [$SIZEH] $YELLOW-->$RESET $(readlink -f "$2"/"$BASE")" # readlink removes double slash
 		pv -$PV "$1" > "$2"/"$BASE" &&
 		syncPermissions "$1" "$2"/"$BASE" &&
-		echo -e "${GREEN}OK$RESET" || echo -e "${RED}ERROR$RESET"
+		echo "${GREEN}OK$RESET" || echo "${RED}ERROR$RESET"
 		exit
 	# file to file
-	elif [ ! -d "$1" ] && [ -r "$1" ]; then
+	# elif [ ! -d "$1" ] && [ -r "$1" ]; then
+	elif isFile "$1" ; then
 		if [ "$(readlink -f "$1")" == "$(readlink -f "$2")" ]; then
 			echoError "Error: Source and destination file is the same."
 		elif [ ! $FORCE ] && [ -f "$2" ]; then
@@ -123,22 +144,26 @@ if [ $# -eq 2 ]; then
 			read -p 'Do you want to overwrite? [y/N] ' input
 			[ "$input" != "y" ] && exit 1
 		fi
+		touch "$2" || echoError "Error: Destination file '$2' could not be created."
 		SIZEH=$(humanReadable $(stat -c%s "$1") 0)
 		[ -z "$SIZEH" ] && SIZEH=$(stat -c%F "$1")
-		echo -e "${YELLOW}File: $RESET$1 [$SIZEH] $YELLOW-->$RESET $(readlink -f "$2")" # readlink removes double slash
+		echo "${YELLOW}File: $RESET$1 [$SIZEH] $YELLOW-->$RESET $(readlink -f "$2")" # readlink removes double slash
 		pv -$PV "$1" > "$2" &&
 		syncPermissions "$1" "$2" &&
-		echo -e "${GREEN}OK$RESET" || echo -e "${RED}ERROR$RESET"
+		echo "${GREEN}OK$RESET" || echo "${RED}ERROR$RESET"
 		exit
 	fi
 fi
 
-DST=${@: -1} # last argument
+DST=${@: -1} # last argument (directory)
 
-if [ ! -d "$DST" ]; then
+if [ -e "$DST" ] && [ ! -d "$DST" ]; then
+	echoError "Error: Target '$DST' is not a directory and already exist. Please remove first."
+elif [ ! -d "$DST" ]; then
 	[ $VERBOSE ] && echo "${YELLOW}Creating directory: $RESET$DST"
 	mkdir -p "$DST" 2> /dev/null || echoError "Error: Could not create directory '$DST'."
 else
+	[ ! -w "$DST" ] && echoError "Error: Destination directory '$DST' is not writeable."
 	if [ ! $FORCE ]; then
 		echo "Destination directory '$DST' already exist." >&2
 		read -p 'Files/Directorys in '$DST' will be overwritten! Continue? [y/N] ' input
@@ -155,29 +180,32 @@ for i in "$@"; do
 	[ $# == $j ] && break
 	
 	iBASE=$(basename "$i")
-	if [ -f "$i" ]; then
+	#if [ -f "$i" ]; then
+	if isFile "$i"; then
 		# file to file
+		touch "$DST"/"$iBASE" || echoError "Error: Destination file '$2' could not be created."
 		SIZEH=$(humanReadable $(stat -c%s "$i") 0)
 		[ -z "$SIZEH" ] && SIZEH=$(stat -c%F "$i")
 		echo "${YELLOW}File: $RESET$i [$SIZEH] $YELLOW-->$RESET $(readlink -f "$DST"/"$iBASE")" # readlink removes double slash
 		pv -$PV "$i" > "$DST"/"$iBASE" &&
-		syncPermissions "$i" "$DST"/"$iBASE" && echo -e "${GREEN}OK$RESET" || echo -e "${RED}ERROR$RESET"
+		syncPermissions "$i" "$DST"/"$iBASE" && echo "${GREEN}OK$RESET" || echo "${RED}ERROR$RESET"
 	elif [ -d "$i" ]; then
 		SIZE=$(du -sb "$i" | grep -oP '^[0-9]+')
 		SIZEH=$(humanReadable $SIZE 0)
 		[ $VERBOSE ] && TAR=cvC || TAR=cC
 		if [ $# -eq 2 ]; then
 			# 1 dir to 1 dir
-			echo -e "${YELLOW}Directory:$RESET $i [$SIZEH] $YELLOW-->$RESET $(readlink -f "$DST")" # readlink removes double slash
-			tar $TAR "$i" . | pv -${PV}s $SIZE | tar xC "$DST" && echo -e "${GREEN}OK$RESET" || echo -e "${RED}ERROR$RESET"
+			echo "${YELLOW}Directory:$RESET $i [$SIZEH] $YELLOW-->$RESET $(readlink -f "$DST")" # readlink removes double slash
+			tar $TAR "$i" . | pv -${PV}s $SIZE | tar xC "$DST" && echo "${GREEN}OK$RESET" || echo "${RED}ERROR$RESET"
 		else
 			# dir to dir
 			echo "${YELLOW}Directory:$RESET $i [$SIZEH] $YELLOW-->$RESET $(readlink -f "$DST"/$(basename "$i"))" # readlink removes double slash
-			tar $TAR "$(dirname "$i")" $iBASE | pv -${PV}s $SIZE | tar xC "$DST" && echo -e "${GREEN}OK$RESET" || echo -e "${RED}ERROR$RESET"
+			tar $TAR "$(dirname "$i")" $iBASE | pv -${PV}s $SIZE | tar xC "$DST" && echo "${GREEN}OK$RESET" || echo "${RED}ERROR$RESET"
 		fi
 	else
 		echo >&2
-		echo "${RED}Error. '$i' is not a file or directory.$RESET" >&2
+		echo "${RED}Error: '$i' is not a file or directory.$RESET" >&2
+		echo "${RED}Type: $(stat -c%F "$i")$RESET" >&2
 		echo >&2
 		echo "${YELLOW}What did you try to do? Please report :) THX$RESET" >&2
 		exit 1
