'trash': empty scripts consolidated

diff --git a/trash-empty b/trash-empty
--- a/trash-empty
+++ b/trash-empty
@@ -5,7 +5,30 @@ set -ueo pipefail
 # set default directory if $TRASHDIR is not given
 TRASHDIR=${TRASHDIR:-~/.trash}
 
-hash rm 2>/dev/null || { echo "Error: Binary 'rm' is missing."; echo; exit 1; } >&2
+checkBinarys() {
+	for i in "$@"; do
+		hash "$i" 2>/dev/null || {
+			echo "Error: Binary '$i' is missing."
+			echo
+			exit 1
+		} >&2
+	done
+}
+
+checkBinarys "find" "shred" "rm"
+
+# shred files?
+if [ $# -eq 1 ] && [ "$1" == '--shred' ]; then
+	# shred all files, skip if link count is > 1
+	find "$TRASHDIR" -type f -links 1 -exec shred -vn 1 "{}" \;
+elif [ $# -gt 0 ]; then
+	# get file extensions from command line arguments
+	# shred files matching extension, skip if link count is > 1
+	SHRED=("$@")
+	for i in "${SHRED[@]}"; do
+		find "$TRASHDIR" -type f -links 1 -iname "*.$i" -exec shred -vn 1 -s 100K "{}" \;
+	done
+fi
 
 echo Deleting files..
 rm -rf "$TRASHDIR"
