trash: basename dependency removed; code optimized

diff --git a/trash b/trash
--- a/trash
+++ b/trash
@@ -5,18 +5,21 @@
 # It moves files/directorys to a defined directory instead of removing them from the filesystem.
 # If you really want to get rid of them, you can use the trash-empty command.
 
-# Version:  0.31
-# Build:    2020-01-05
+# Version:  0.40
+# Build:    2022-12-11
 # Author:   Heiko Barth
-# Licence:  Beer-Ware (See: http://en.wikipedia.org/wiki/Beerware)
+# Licence:  Beer-Ware (See: https://en.wikipedia.org/wiki/Beerware)
 
 APP=${0##*/}
-VER=0.31
+VER=0.40
 
 set -ueo pipefail
 
-# set default directory if $TRASHDIR is not given
-TRASHDIR=${TRASHDIR:-~/.trash}
+if [ -z "${TRASHDIR:-}" ]; then
+	echo 'Error: $TRASHDIR is not set.'
+	echo
+	exit 1
+fi >&2
 
 checkBinarys() {
 	for i in "$@"; do
@@ -39,15 +42,16 @@ checkBinarys() {
 	echo
 	echo "Syntax: $APP-empty [options]"
 	echo
-	echo "Empty trash:                                 $APP-empty"
-	echo "Empty trash, shred some file types before:   $APP-empty zip rar"
-	echo "Empty trash, shred all files before:         $APP-empty --shred"
+	echo "Empty trash:                             $APP-empty"
+	echo "Shred some file types and empty trash:   $APP-empty txt jpg"
+	echo "Shred all files and empty trash:         $APP-empty --shred"
 	exit 1
 } >&2
 
-checkBinarys "basename" "mkdir" "mv" "stat"
+checkBinarys "mkdir" "mv" "stat"
 
-mkdir -p "$TRASHDIR" 2> /dev/null || {
+# shellcheck disable=SC2174
+mkdir -p -m 700 "$TRASHDIR" 2> /dev/null || {
 	echo "Error: Failed to create directory '$TRASHDIR'."
 	echo
 	exit 1
@@ -67,9 +71,10 @@ for i in "$@"; do
 	fi
 
 	# basename of file or directory
-	NAME=$(basename "$i")
+	NAME=${i##*/}
 
 	# Create target directory
+	# shellcheck disable=SC2174
 	mkdir -p -m 700 "$TRASHDIR/$TODAY" 2> /dev/null || {
 		echo "Error: Failed to create directory '$TRASHDIR/$TODAY'."
 		echo
@@ -91,7 +96,7 @@ for i in "$@"; do
 		done
 	else
 		mv "$i" "$TRASHDIR/$TODAY/$NAME" || {
-			echo "Error: Failed move '$i' --> '$TRASHDIR/$TODAY/$NAME'"
+			echo "Error: Failed to move '$i' --> '$TRASHDIR/$TODAY/$NAME'"
 			FAIL=1
 		} >&2
 	fi
diff --git a/trash-empty b/trash-empty
--- a/trash-empty
+++ b/trash-empty
@@ -2,8 +2,11 @@
 
 set -ueo pipefail
 
-# set default directory if $TRASHDIR is not given
-TRASHDIR=${TRASHDIR:-~/.trash}
+if [ -z "${TRASHDIR:-}" ]; then
+	echo 'Error: $TRASHDIR is not set.'
+	echo
+	exit 1
+fi >&2
 
 checkBinarys() {
 	for i in "$@"; do
@@ -26,11 +29,11 @@ if [ $# -eq 1 ] && [ "$1" == '--shred' ]; then
 elif [ $# -gt 0 ]; then
 	# get file extensions from command line arguments
 	# shred files matching extension, skip if link count is > 1
-	SHRED=("$@")
-	for i in "${SHRED[@]}"; do
-		find "$TRASHDIR" -type f -links 1 -iname "*.$i" -exec shred -vn 1 -s 100K "{}" \;
+	for i in "$@"; do
+		find "$TRASHDIR" -type f -links 1 -iname "*.$i" -exec shred -vn 1 "{}" \;
 	done
 fi
 
-echo Deleting files..
+echo "Deleting files.."
 rm -rf "$TRASHDIR"
+echo
